import ProductsFilter from "@/components/main/shop/ProductsFilter";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const AboutPage = () => {
  return (
    <div className="flex-grow mt-20 lg:mt-28">
      <div className="container-custom py-8">
        <div className="h-32 bg-primary-foreground rounded-lg"></div>
        <ProductsFilter />
      </div>
    </div>
  );
};

export default AboutPage;
