import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const AboutPage = () => {
  return <div className="flex-grow mt-20 lg:mt-28"></div>;
};

export default AboutPage;
