import Contact from "@/components/main/contact/Contact";
import Map from "@/components/main/contact/Map";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ContactPage = () => {
  return (
    <div className="flex-grow mt-20 lg:mt-28">
      <div className=" bg-primary-foreground py-16">
        <div className="container-custom">
          <h1 className="text-4xl md:text-5xl font-bold text-center mb-4">
            Contact Us
          </h1>
          <p className="text-lg text-center max-w-2xl mx-auto text-petio-text">
            We'd love to hear from you! Send us a message and we'll respond as
            soon as possible.
          </p>
        </div>
      </div>
      <Contact />
      <Map />
    </div>
  );
};

export default ContactPage;
