import { Metadata } from "next";
import React from "react";
import About from "@/components/main/about/About";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const AboutPage = () => {
  return <About />;
};

export default AboutPage;
