import BlogSection from "@/components/main/home/BlogSection";
import CategoryBanner from "@/components/main/home/CategoryBanner";
import FeaturedProducts from "@/components/main/home/FeaturedProducts";
import Hero from "@/components/main/home/Hero";
import NewArrivals from "@/components/main/home/NewArrivals";
import Newsletter from "@/components/main/Newsletter";
import PromoBanner from "@/components/main/home/PromoBanner";
import Services from "@/components/main/home/Services";
import Testimonials from "@/components/main/home/Testimonials";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Crunchies",
  description: "Generated by create next app",
  openGraph: {
    title: "Crunchies",
    description: "Generated by create next app",
    type: "website",
    url: "https://example.com",
    siteName: "Crunchies",
    images: "https://example.com/open-graph.png",
  },
};

const HomePage = () => {
  return (
    <main className="flex-grow mt-20 lg:mt-28">
      <Hero />
      <CategoryBanner />
      <FeaturedProducts />
      <PromoBanner />
      <NewArrivals />
      <Services />
      <Testimonials />
      <BlogSection />
      <Newsletter />
    </main>
  );
};

export default HomePage;
